project_name: InstructLab
repo_url: https://github.com/instructlab/.github
commit_id: 83d9852ad97c6b27d4b24508f7cfe7ff5dd04d0d
patterns:
  - README.md
  - "**/*.md"
  - "**/*.txt"
  - "**/*.yaml"
yaml_path: qna.yaml
max_files: 100
max_lines: 2000
keywords:
  - InstructLab
  - getting started
  - problems
  - created
  - collaboration
  - open source
  - tuning method
  - mission
min_sentence_length: 5
min_answers: 5
questions:
  - "What is {project_name}?"
  - "How to get started with {project_name}?"
  - "What problems is {project_name} aiming to solve?"
  - "Who created {project_name}?"
  - "How does {project_name} enable community collaboration?"
  - "Is {project_name} an open-source project?"
  - "What is the tuning method for {project_name}?"
  - "What is the mission of {project_name}?"
  - "What technologies or programming languages is {project_name} developed in?"
  - "What are the key features of {project_name}?"
  - "What are the current limitations of {project_name}?"
  - "How can contributors improve {project_name}?"
  - "What are the future goals for {project_name}?"
  - "How is {project_name} maintained and updated?"
  - "What are the recommended best practices for using {project_name}?"
  - "What are the main challenges faced by {project_name}?"
chat:
  enabled: true
  model: "deepset/roberta-base-squad2"
generate:
  enabled: true
  model: "deepset/roberta-base-squad2"
  taxonomy_path: "~/instructlab/taxonomy"
  taxonomy_base: "~/instructlab/taxonomy"
serve:
  enabled: true
  model_path: "~/instructlab/models/roberta-base-squad2"
taxonomy_dir: "~/instructlab/taxonomy"
model_name: "deepset/roberta-base-squad2" # Primary model to use for question answering
optimize: true # Flag to indicate whether to run optimization
model_list: # List of models to use for optimization
  - "deepset/roberta-base-squad2"
  - "bert-large-uncased-whole-word-masking-finetuned-squad"
  - "ibm/re2g-reranker-trex"
  - "ibm/merlinite-7b"
  - "ibm/labradorite-13b"
# Available models:
# - "deepset/roberta-base-squad2"
# - "bert-large-uncased-whole-word-masking-finetuned-squad"
# - "distilbert-base-cased-distilled-squad"
# - "albert-base-v2"
# - "t5-base"
# - "ibm/labradorite-13b"
# - "ibm/merlinite-7b"
# - "ibm/re2g-reranker-trex"
#
# To find more models, visit https://huggingface.co/models
# https://huggingface.co/models?pipeline_tag=question-answering
