title: InstructLab-QA-Generator
email: {{ secrets.SITE_EMAIL }}
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for InstructLab-QA-Generator

baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://tosin2013.github.io/InstructLab-QA-Generator" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tech0827
github_username: tosin2013

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Just the Docs configuration
aux_links:
  "View on GitHub":
    - "https://github.com/tosin2013/InstructLab-QA-Generator"
aux_links_new_tab: true
heading_anchors: true

# Enable collection for categories
collections:
  category:
    output: true

# Default layout for category pages
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category
