name: Generate QnA YAML and Serve Model

on:
  workflow_dispatch:

jobs:
  generate_qna:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython pyyaml transformers nltk
        pip install git+https://github.com/instructlab/instructlab.git@v0.17.1

    - name: Run QnA Generation Script
      run: |
        python generate_project_qa.py --config_path config.yaml

    - name: Initialize ilab
      run: |
        cd ~/instructlab
        python -m venv venv
        source venv/bin/activate
        ilab init

    - name: Download the model
      run: |
        cd ~/instructlab
        source venv/bin/activate
        ilab download --repository instructlab/granite-7b-lab-GGUF --filename=granite-7b-lab-Q4_K_M.gguf

    - name: Serve the model
      run: |
        cd ~/instructlab
        source venv/bin/activate
        ilab serve --model-path models/granite-7b-lab-Q4_K_M.gguf &
        sleep 60  # Wait for the server to start

    - name: Generate synthetic data
      run: |
        cd ~/instructlab
        source venv/bin/activate
        ilab generate --num-instructions ${{ github.event.inputs.num_instructions }} --input-yaml ${{ github.event.inputs.yaml_path }}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output.yaml
        git commit -m "Generated QnA YAML file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
