name: Generate QnA YAML and Serve Model

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project'
        required: true
        default: 'InstructLab'
      repo_url:
        description: 'GitHub repository URL'
        required: true
        default: 'https://github.com/instructlab/.github'
      commit_id:
        description: 'Commit ID to checkout'
        required: true
        default: '83d9852ad97c6b27d4b24508f7cfe7ff5dd04d0d'
      max_files:
        description: 'Maximum number of files to read'
        required: true
        default: 100
      max_lines:
        description: 'Maximum number of lines to read from each file'
        required: true
        default: 2000
      keywords:
        description: 'Keywords to search for relevant sections'
        required: true
        default: 'InstructLab,getting started,problems,created,collaboration,open source,tuning method,mission'
      min_sentence_length:
        description: 'Minimum number of words in the answer'
        required: true
        default: 10
      min_answers:
        description: 'Minimum number of valid answers required'
        required: true
        default: 5
      num_instructions:
        description: 'Number of instructions to generate'
        required: true
        default: 100

jobs:
  generate_qna:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython pyyaml transformers nltk
        pip install git+https://github.com/instructlab/instructlab.git@v0.17.1

    - name: Run QnA Generation Script
      run: |
        python generate_project_qa.py
      env:
        PROJECT_NAME: ${{ github.event.inputs.project_name }}
        REPO_URL: ${{ github.event.inputs.repo_url }}
        COMMIT_ID: ${{ github.event.inputs.commit_id }}
        PATTERNS: ${{ github.event.inputs.patterns }}
        YAML_PATH: ${{ github.event.inputs.yaml_path }}
        MAX_FILES: ${{ github.event.inputs.max_files }}
        MAX_LINES: ${{ github.event.inputs.max_lines }}
        KEYWORDS: ${{ github.event.inputs.keywords }}
        MIN_SENTENCE_LENGTH: ${{ github.event.inputs.min_sentence_length }}
        MIN_ANSWERS: ${{ github.event.inputs.min_answers }}

    - name: Initialize ilab
      run: |
        cd ~/instructlab
        python -m venv venv
        source venv/bin/activate
        ilab init

    - name: Download the model
      run: |
        cd ~/instructlab
        source venv/bin/activate
        ilab download --repository instructlab/granite-7b-lab-GGUF --filename=granite-7b-lab-Q4_K_M.gguf

    - name: Serve the model
      run: |
        cd ~/instructlab
        source venv/bin/activate
        ilab serve --model-path models/granite-7b-lab-Q4_K_M.gguf &
        sleep 60  # Wait for the server to start

    - name: Generate synthetic data
      run: |
        cd ~/instructlab
        source venv/bin/activate
        ilab generate --num-instructions ${{ github.event.inputs.num_instructions }} --input-yaml ${{ github.event.inputs.yaml_path }}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output.yaml
        git commit -m "Generated QnA YAML file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
